version: '2.3'

services:
  db:
    image: postgres:12.2-alpine
    container_name: "comments-database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data  # Corrected the volume mount point

  api:
    build: .
    container_name: "comments-rest-api"
    environment:
      - DB_USERNAME=postgres  # Removed unnecessary quotes
      - DB_PASSWORD=postgres
      - DB_DB=postgres
      - DB_TABLE=postgres
      - DB_PORT=5432
      - SSL_MODE=disable  # Corrected the typo
    ports:
      - "8090:8090"
    depends_on:
      - db
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge
